name:                lambda-haskell-sample
version:             0.1.0
github:              "rinse/lambda-haskell-sample"
license:             BSD3
author:              "rinse"
maintainer:          "rinse@neko2.net"
copyright:           "2020 rinse"

description:         Please see the README on GitHub at <https://github.com/rinse/lambda-haskell-sample#readme>

dependencies:
- base >= 4.7 && < 5
- aws-lambda-haskell-runtime >= 3.0.0
- aws-lambda-haskell-runtime-wai
- aeson
- http-types
- wai
- warp

library:
  source-dirs: src

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -static
#   - -static -optl-static -optl-pthread -fPIC
    - -with-rtsopts=-N
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
    - lambda-haskell-sample

# Executables for dev is placed as the test comptype.
# This is because all of the executable comps will be built when any exe component is built.
# https://docs.haskellstack.org/en/stable/build_command/#target-syntax
tests:
  lambda-haskell-sample-dev:
    main:                Main.hs
    source-dirs:         dev
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - lambda-haskell-sample


default-extensions:
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
